### ISSUE TITLE
java.util.HashMap cannot be cast to org.apache.kafka.connect.data.Struct

### ISSUE THREAD

**Issue by mashannon168** [jeff-svds/kafka-connect-opentsdb#2]
Hi, 

I am getting this error, 

23:26| ERROR | WorkerSinkTask.java 401 | Task tsdb-sink-1 threw an uncaught and unrecoverable exception
java.lang.ClassCastException: java.util.HashMap cannot be cast to org.apache.kafka.connect.data.Struct
        at com.svds.kafka.connect.opentsdb.OpenTsdbSinkTask$$anonfun$1.apply(OpenTsdbSinkTask.scala:40)
        at com.svds.kafka.connect.opentsdb.OpenTsdbSinkTask$$anonfun$1.apply(OpenTsdbSinkTask.scala:38)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.Iterator$class.foreach(Iterator.scala:893)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at com.svds.kafka.connect.opentsdb.OpenTsdbSinkTask.put(OpenTsdbSinkTask.scala:38)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:381)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:227)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:170)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:142)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:140)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)

when i use console consume i see, i put as string/text, is that ok?

{"metric":"VOLUME", "timestamp":"1475508180000", "value":"15", "tags": {"SEGMENT":"580-GREEE", "STATION":"580-RTMS-GREEE15_3" } }
{"metric":"VOLUME", "timestamp":"1475508180000", "value":"15", "tags": {"SEGMENT":"580-GREEE", "STATION":"580-RTMS-GREEE15_4" } }
{"metric":"VOLUME", "timestamp":"1475508180000", "value":"15", "tags": {"SEGMENT":"580-GREEE", "STATION":"580-RTMS-GREEE15_5" } }
{"metric":"VOLUME", "timestamp":"1475508180000", "value":"6", "tags": {"SEGMENT":"580-GREEW", "STATION":"580-LOOP-GREEW01_21_21" } }

Thanks
Shannon

**Comment by mashannon168** [comment]
I see your produce example, do i need to use avro for value? i use jsonconverter for value convert class.

**Comment by mashannon168** [comment]
If change to avro i am getting

23:43| ERROR | WorkerTask.java 142 | Task tsdb-sink-2 threw an uncaught and unrecoverable exception
org.apache.kafka.connect.errors.DataException: Failed to deserialize data to Avro:
        at io.confluent.connect.avro.AvroConverter.toConnectData(AvroConverter.java:109)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:357)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:226)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:170)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:142)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:140)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

Do i need to register the schema?

**Comment by rmoff** [comment]
Some notes on this: https://rmoff.net/2020/01/22/kafka-connect-classcastexception/
